<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\CommentBundle\Entity;

use FOS\CommentBundle\Model\SignedCommentInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Sonata\CommentBundle\Entity\BaseComment as BaseComment;
use Doctrine\ORM\Mapping AS ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Comment extends BaseComment implements SignedCommentInterface {

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Author of the comment
     *
     * @ORM\ManyToOne(targetEntity="DaVinci\TaxiBundle\Entity\User")
     * @var User
     */
    protected $author;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId() {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function setAuthor(UserInterface $author) {
        $this->author = $author;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthor() {
        return $this->author;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthorName() {
        return $this->getAuthor() ? $this->getAuthor()->getUsername() : 'Anonymous';
    }

    /**
     * Thread of this comment
     *
     * @var Thread
     * @ORM\ManyToOne(targetEntity="Application\Sonata\CommentBundle\Entity\Thread")
     */
    protected $thread;

}
