services:
    davinci.taxi.admin.countrycity:
        class: DaVinci\TaxiBundle\Admin\CountryCityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: sonata_countries }
        arguments:
            - null
            - DaVinci\TaxiBundle\Entity\Admin\CountryCity
            - SonataAdminBundle:CRUD
            
    davinci.taxi.admin.profitpage:
        class: DaVinci\TaxiBundle\Admin\ProfitPageAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: sonata.admin.group.content, label: "Profit page tabs" }
        arguments:
            - ''
            - DaVinci\TaxiBundle\Document\ProfitPage
            - SonataAdminBundle:CRUD
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']] 
            - [setRootPath, ['/cms/profit']]     
            
    davinci.taxi.admin.aboutpage:
        class: DaVinci\TaxiBundle\Admin\AboutPageAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: sonata.admin.group.content, label: "About page tabs" }
        arguments:
            - ''
            - DaVinci\TaxiBundle\Document\AboutPage
            - SonataAdminBundle:CRUD
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']] 
            - [setRootPath, ['/cms/about']]     
            
    davinci.taxi.admin.faqentry:
        class: DaVinci\TaxiBundle\Admin\FaqEntryAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: sonata.admin.group.content, label: "FAQs" }
        arguments:
            - ''
            - DaVinci\TaxiBundle\Document\FaqEntry
            - SonataAdminBundle:CRUD
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']] 
            - [setRootPath, ['/cms/faq']]     