services:
    davinci.taxi.admin.countrycity:
        class: DaVinci\TaxiBundle\Admin\CountryCityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: sonata_countries }
        arguments:
            - null
            - DaVinci\TaxiBundle\Entity\Admin\CountryCity
            - SonataAdminBundle:CRUD
            
    davinci.taxi.admin.profitpage:
        class: DaVinci\TaxiBundle\Admin\ProfitPageAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: sonata.admin.group.content, label: "Add profit tab" }
        arguments:
            - ''
            - DaVinci\TaxiBundle\Document\ProfitPage
            - SonataAdminBundle:CRUD
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']] 
            - [setRootPath, ['/cms/profit']]     