<?php

namespace DaVinci\TaxiBundle\Entity\Seo;

/**
 * ParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * @param string $name
     * @return Params|null
     */
    public function findByActionName($name) {
        return $this->findOneBy(
            array('actionName' => $name), 
            array('id' => 'asc')
        );
    }
    
}

?>