<?php

namespace DaVinci\TaxiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine;

/**
 * IndependentDriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndependentDriverRepository extends EntityRepository 
{
    
    public function persist(\DaVinci\TaxiBundle\Entity\IndependentDriver $driver)
	{
		$this->_em->persist($driver);
    }
    
    public function saveAll(\DaVinci\TaxiBundle\Entity\IndependentDriver $driver)
	{
        $this->_em->persist($driver);
        $this->_em->persist($driver->getAddress());
        foreach ($driver->getPhones() as $phone) {
            $this->_em->persist($phone);
        }
               
		$this->_em->flush();
	}
        
    public function save(\DaVinci\TaxiBundle\Entity\IndependentDriver $driver)
	{
		$this->_em->persist($driver);
		$this->_em->flush();
	}
	
	/**
	 * @param integer $userId
	 * @return \DaVinci\TaxiBundle\Entity\IndependentDriver
	 */
	public function findOneByUserId($userId)
	{
		$query = $this->_em->createQuery("
			SELECT
				driver
			FROM
				DaVinci\TaxiBundle\Entity\IndependentDriver driver
			WHERE
				driver.user = :userId
		");
		$query->setParameters(array('userId' => $userId));
		
		return $query->getOneOrNullResult();
	}
	
}