<?php

namespace DaVinci\TaxiBundle\Entity;

/**
 * MessageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageContentRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * @param string $literalCode
     * @param string $recipient
	 * @return Ambigous <NULL, \DaVinci\TaxiBundle\Entity\MessageContent>
	 */
	public function findByLiteralCodeAndRecipient($literalCode, $recipient)
	{
		$query = $this->_em->createQuery("
			SELECT
				message
			FROM
				DaVinci\TaxiBundle\Entity\MessageContent message
			WHERE
				message.literalCode = :literalCode
                AND message.recipient = :recipient
		");
		$query->setParameters(array(
            'literalCode' => $literalCode,
            'recipient' => $recipient
        ));
		
		return $query->getOneOrNullResult();		
	}
	
}
