<?php

namespace DaVinci\TaxiBundle\Entity;

/**
 * MessageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageContentRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * @param string $literalCode
	 * @return Ambigous <NULL, \DaVinci\TaxiBundle\Entity\MessageContent>
	 */
	public function findByLiteralCode($literalCode)
	{
		$query = $this->_em->createQuery("
			SELECT
				message
			FROM
				DaVinci\TaxiBundle\Entity\MessageContent message
			WHERE
				message.literalCode = :literalCode			
		");
		$query->setParameter('literalCode', $literalCode);
		
		return $query->getOneOrNullResult();		
	}
	
}
