<?php

namespace DaVinci\TaxiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine;

/**
 * PassengerRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRequestRepository extends EntityRepository
{
	
	const DEFAULT_INTERVAL_HOURS = 24;
	const DEFAULT_LIMIT_ROWS = 10;
	
	/**
	 * @param \DaVinci\TaxiBundle\Entity\PassengerRequest $request
	 * @return void
	 */
	public function create(\DaVinci\TaxiBundle\Entity\PassengerRequest $request)
	{
		$this->_em->persist($request);
		
		$vehicleOptions = $request->getVehicleOptions();
		$vehicleOptions->setPassengerRequest($request);
		$this->_em->persist($vehicleOptions);
		foreach ($vehicleOptions->getChildSeats() as $seat) {
			if ($seat->getChildSeatNumber() <= 0) {
				continue;
			}
		
			$seat->setVehicleOptions($vehicleOptions);
			$this->_em->persist($seat);
		}
		foreach ($vehicleOptions->getPetCages() as $cage) {
			if ($cage->getPetCageNumber() <= 0) {
				continue;
			}
		
			$cage->setVehicleOptions($vehicleOptions);
			$this->_em->persist($cage);
		}
		
		foreach ($request->getRoutePoints() as $routePoint) {
			$routePoint->setPassengerRequest($request);
			$this->_em->persist($routePoint);
		}
		
		$vehicle = $request->getVehicle();
		$vehicle->setPassengerRequest($request);
		$this->_em->persist($vehicle);
		 
		$tariff = $request->getTariff();
		$tariff->setPassengerRequest($request);
		$this->_em->persist($tariff);
		 
		$passengerDetail = $request->getPassengerDetail();
		$passengerDetail->setPassengerRequest($request);
		$this->_em->persist($passengerDetail);
		 
		$vehicleServices = $request->getVehicleServices();
		$vehicleServices->setPassengerRequest($request);
		$this->_em->persist($vehicleServices);
		 
		$vehicleDriverConditions = $request->getVehicleDriverConditions();
		$vehicleDriverConditions->setPassengerRequest($request);
		$this->_em->persist($vehicleDriverConditions);
		 
		$this->_em->flush();
	}
	
	public function save(\DaVinci\TaxiBundle\Entity\PassengerRequest $request)
	{
		$this->_em->persist($request);
		$this->_em->flush();
	}
	
	public function getAllUserRequestsByState($userId, $state)
	{
		$query = $this->_em->createQuery("
			SELECT 
				req 
			FROM 
				DaVinci\TaxiBundle\Entity\PassengerRequest req
			JOIN
				DaVinci\TaxiBundle\Entity\RoutePoint point	 
			WHERE 
				req.user = :userId AND req.stateValue = :stateValue 
			ORDER BY 
				req.id DESC
		");
		$query->setParameters(array(
			'userId' => $userId,
			'stateValue' => $state
		));
		
		return $query->getResult();
	}
	
	public function getAllUserRequestsByStates($userId, array $states)
	{		
		$query = $this->_em->createQuery("
			SELECT
				req
			FROM
				DaVinci\TaxiBundle\Entity\PassengerRequest req
			JOIN
				req.routePoints points
			WHERE
				req.user = :userId AND req.stateValue IN (:stateValues)
			ORDER BY 
				req.id DESC
		");
		$query->setParameters(array(
			'userId' => $userId,
			'stateValues' => $states	
		));
	
		return $query->getResult();
	}
	
	public function getActualRequestsByStates(array $states)
	{
		$query = $this->_em->createQuery("
			SELECT
				req
			FROM
				DaVinci\TaxiBundle\Entity\PassengerRequest req
			JOIN
				req.routePoints points
			JOIN
				req.tariff tariff	
			WHERE
				DATE_DIFF(req.pickUp, :pickUp) > 0
				AND req.stateValue IN (:stateValues)
			ORDER BY
				req.id DESC	
		");
		$query->setParameter(
			'pickUp', 
			new \DateTime("+" . self::DEFAULT_INTERVAL_HOURS . " hours"), 
			\Doctrine\DBAL\Types\Type::DATETIMETZ
		);
		$query->setParameter('stateValues', $states);
		$query->setMaxResults(self::DEFAULT_LIMIT_ROWS);
									
		return $query->getResult();
	}
	
}
