<?php

namespace DaVinci\TaxiBundle\Entity;

/**
 * TravelCoefficientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelCoefficientRepository extends \Doctrine\ORM\EntityRepository
{		
}
