<?php

namespace DaVinci\TaxiBundle\Entity;

/**
 * UserCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCommentRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByColumnAndState($column, $state)
    {
        return $this->findBy(
            array(
                'type' => UserComment::getTypeByColumn($column),
                'state' => $state
            ), 
            array('createdAt' => 'desc')
        );
    }


    /**
	 * @param \DaVinci\TaxiBundle\Entity\InternalMessage $internalMessage
	 * @return void
	 */
	public function save(\DaVinci\TaxiBundle\Entity\UserComment $comment)
	{
		$this->_em->persist($comment);
		$this->_em->flush();
	}
    
}
