fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: DaVinci\TaxiBundle\Entity\User
    group:
        group_class:  DaVinci\TaxiBundle\Entity\Group
        # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
        # group_manager: sonata.user.orm.group_manager                    
    service:
        user_manager: custom_user_manager
        mailer: da_vinci_taxi.custom_mailer
    registration:
        form:
            type: taxi_user_registration
            # handler: taxi.registration.form.handler
            # validation_groups: [DaVinciRegistration]
            # seted in RegistrationController
        confirmation: 
            enabled: true 
    profile:
        form:
            type: taxi_user_profile
            validation_groups: [DaVinciProfile]

    from_email:
        address:        noreply@taximyprice.com
        sender_name:    TaxiMyPrice