imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    
    # FriendOfSymfony Bundles
    - { resource: fos/fos_comment.yml }
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }
    
    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # Knp Paginator
    - { resource: knp/knp_paginator.yml }
    
    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }

   # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }
      
    # Sonata e-commerce bundles
    - { resource: sonata/sonata_price.yml }
    - { resource: sonata/sonata_order.yml }
    - { resource: sonata/sonata_payment.yml }
    - { resource: sonata/sonata_product.yml }
    - { resource: sonata/sonata_invoice.yml }
    - { resource: sonata/sonata_delivery.yml }
    - { resource: sonata/sonata_customer.yml }
    - { resource: sonata/sonata_basket.yml }

    - { resource: admin/admin_config.yml }
    - { resource: image/image.yml }
    
    - { resource: @ApplicationSonataProductBundle/Resources/config/product.yml }
    - { resource: requirejs/require_js.yml }
    
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:           %kernel.root_dir%/cache/sessions
    fragments:       ~
    http_method_override: true
    default_locale: en

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    
    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ DaVinciTaxiBundle, FOSUserBundle, HearsayRequireJSBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        types:
           json: Sonata\Doctrine\Types\JsonType
           currency: Sonata\Component\Currency\CurrencyDoctrineType
        mapping_types:
            currency: currency
            enum:       string 
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings: ~
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true

jms_i18n_routing:
    default_locale: en
    locales: [en, ru]
    strategy: prefix_except_default

a2lix_i18n_doctrine:
    manager_registry: doctrine

a2lix_translation_form:
    locales: [en, ru]       # [1]
    required_locales: [en]      # [2]
    manager_registry: doctrine      # [3]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [4]

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    sender_address: "info@taximyprice.com"

jms_security_extra:
    secure_all_services: false

jms_serializer:
    metadata:
        directories:
            - { path: %kernel.root_dir%/../vendor/sonata-project/user-bundle/Sonata/UserBundle/Resources/config/serializer/FOSUserBundle, namespace_prefix: 'FOS\UserBundle' }

knp_menu:
    twig:
        template: DaVinciTaxiBundle:Menu:knp_menu.html.twig

nelmio_api_doc: ~

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters:  true }


parameters:
    api_caller.options:
        timeout: 10  # maximum transport + execution duration of the call in sec.
        ssl_verifypeer: false  # to stop cURL from verifying the peer's certificate.
        useragent: "TaxiMyPrice Caller"  # contents of the "User-Agent: " header.
        followlocation: true  # to follow any "Location: " header that the server sends.
        sslversion: 3  # set to 3 to avoid any bugs that relate to automatic version selection.
        fresh_connect: false  # set to true to force full reconnect every call.
