da_vinci_taxi_homepage:
    pattern:  /
    defaults: { _controller: DaVinciTaxiBundle:Home:index }
    
# offices, registrations
userbundle:
    resource: '@DaVinciUserBundle/Resources/config/routing.yml'
    
taxibundle:
    resource: '@DaVinciTaxiBundle/Resources/config/routing.yml'

#admin panel
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news