security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 12
        FOS\UserBundle\Model\UserInterface: 
            algorithm: bcrypt
            cost: 12
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                        admin:  { password: $2a$12$EAvhTPErv3Kr04dWgixXhOoMidDaXCr3sA71ojSgq6R6GONdIX7c6, roles: 'ROLE_ADMIN' }
        fos_userbundle:
            id: phoneemail_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_provider: form.csrf_provider
             #   always_use_default_target_path: false
             #   default_target_path:            /
            logout:       true
            anonymous:    true
        
        default:
            anonymous: ~
           
    role_hierarchy:
        ROLE_TAXIDRIVER:  ROLE_USER
        ROLE_COMPANYDRIVER: ROLE_USER
        ROLE_TAXIMANAGER: ROLE_USER
        ROLE_TAXICOMPANY: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }