#
# more information can be found here http://sonata-project.org/bundles/admin
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      ' '
    title_logo: bundles/davincitaxi/images/logo.png
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display

    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        # ApplicationSonataAdminBundle::demo_layout.html.twig
        layout:  SonataAdminBundle::standard_layout.html.twig 
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        
        # fix admin bundle!!!!! try to DELETE when updated
        base_list_field: ApplicationSonataAdminBundle:CRUD:base_list_field.html.twig
           
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata_admin_doctrine_phpcr.tree_block }    
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
            - { position: center, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> TaxiMyPrice admin panel"} }
          #  - { position: center, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25 }}
          #  - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}

        groups:
            sonata.admin.group.content:
                label:           sonata_content
                label_catalogue: DaVinciTaxiBundle
                items:
                    - sonata.media.admin.media
                    #- sonata.media.admin.gallery
                    - davinci.taxi.admin.profitpage    
                    - davinci.taxi.admin.aboutpage       
                    - davinci.taxi.admin.faqentry   
                    - davinci.taxi.admin.guidepage   
                    - davinci.taxi.admin.videoguidepage     
                    - davinci.taxi.admin.comment

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.notification.admin.message   
                    - davinci.taxi.admin.countrycity
            
           # simplecms:
           #     label: Simple CMS
           #     items:
           #         - cmf_simple_cms.persistence.phpcr.admin.page
            routing:
                label: URLs
                items:
                    - cmf_routing.route_admin
                    - cmf_routing.redirect_route_admin    
            #content:
            #    label: Content
            #    items:
            #        - cmf_content.admin
#                    - cmf_block.simple_admin
#                    - cmf_block.container_admin
#                    - cmf_block.reference_admin
#                    - cmf_block.action_admin
#                    - cmf_block.imagine.slideshow_admin
#                    - cmf_block.imagine.imagine_admin     
    assets:
        stylesheets:
            # Defaults:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonatatranslation/css/sonata-translation.css 
            - bundles/davincitaxi/js/intl-tel-input-master/css/intlTelInput.css    

        javascripts:
            # Defaults:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataadmin/treeview.js  
            - bundles/davincitaxi/js/intl-tel-input-master/js/intlTelInput.js  

            - bundles/ivoryckeditor/ckeditor.js
            - bundles/a2lixtranslationform/js/a2lix_translation_bootstrap.js
            - bundles/davincitaxi/js/admin/custom.js      
            - bundles/cmftreebrowser/js/admin_tree.js

    extensions:
            cmf_core.admin_extension.child:
                implements:
                    - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
                    - Doctrine\ODM\PHPCR\HierarchyInterface    
            cmf_core.admin_extension.publish_workflow.time_period:
                implements:
                    - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
            cmf_core.admin_extension.publish_workflow.publishable:
                implements:
                    - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
            cmf_core.admin_extension.translatable:
                implements:
                    - Symfony\Cmf\Bundle\CoreBundle\Translatable\TranslatableInterface
#            cmf_menu.admin_extension.menu_node_referrers:
#                implements:
#                    - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
            cmf_routing.admin_extension.route_referrers:
                implements:
                    - Symfony\Cmf\Component\Routing\RouteReferrersInterface
            cmf_routing.admin_extension.frontend_link:
                implements:
                    - Symfony\Cmf\Component\Routing\RouteReferrersReadInterface
                extends:
                    - Symfony\Component\Routing\Route
            cmf_seo.admin_extension:
                implements:
                    - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface
                    
sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
#        Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page:
#            valid_children:
#                - Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:
            valid_children: []
        DaVinci\TaxiBundle\Document\ProfitPage:
            valid_children:
                - DaVinci\TaxiBundle\Document\ProfitPage  
        DaVinci\TaxiBundle\Document\AboutPage:
            valid_children:
                - DaVinci\TaxiBundle\Document\AboutPage      