imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: %locales%
    default_locale: en
    # here enable the types you need
    gedmo:
        enabled: true
    phpcr:
        enabled: true