# 
# more information can be found here http://sonata-project.org/bundles/news
#
sonata_news:
    title:        TaxiMyPrice blog
    link:         http://taximyprice.com/
    description:  TaxiMyPrice news
    salt:         'rgerg4g34t34t35hynmui9786'

    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.collection
    permalink:
        date:     %%1$04d/%%2$02d/%%3$02d/%%4$s => 2012/02/01/slug
    # comment options
    comment:
        notification:
            emails:   [icevita@taximyprice.com, icevita@gmail.com]
            from:     no-reply@taximyprice.com
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'
            
    class:
 #       post:       Application\Sonata\NewsBundle\Entity\Post
 #       comment:    Application\Sonata\NewsBundle\Entity\Comment
        media:      Application\Sonata\MediaBundle\Entity\Media
        user:       DaVinci\TaxiBundle\Entity\User


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~
    dbal:
    # ...
        types:
            json: Sonata\Doctrine\Types\JsonType