da_vinci_taxi_homepage:
    resource: "@DaVinciTaxiBundle/Controller/HomeController.php"
    type: annotation
    
main_driver:
    pattern:  /main-driver
    defaults: { _controller: DaVinciTaxiBundle:Home:main_driver }    
