da_vinci_taxi_homepage:
    pattern:  /
    defaults: { _controller: DaVinciTaxiBundle:Home:index }
    
order_step_1:
    pattern:  /order_step_1
    defaults: { _controller: DaVinciTaxiBundle:Home:order_step_1 }
order_step_2:
    pattern:  /order_step_2
    defaults: { _controller: DaVinciTaxiBundle:Home:order_step_2 }
order_step_3:
    pattern:  /order_step_3
    defaults: { _controller: DaVinciTaxiBundle:Home:order_step_3 }
main_driver:
    pattern:  /main_driver
    defaults: { _controller: DaVinciTaxiBundle:Home:main_driver }    

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
fos_user_registration_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    methods:  [GET,POST]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
    
 
register_company:
    pattern: /register-company 
    defaults: { _controller: DaVinciTaxiBundle:Office:register_company }
register_independent_driver:
    pattern: /register-independent-driver
    defaults: { _controller: DaVinciTaxiBundle:Office:register_independent_driver }
register_manager:
    pattern: /register-manager
    defaults: { _controller: DaVinciTaxiBundle:Office:register_manager }
register_company_driver:
    pattern: /register-company-driver
    defaults: { _controller: DaVinciTaxiBundle:Office:register_company_driver }
    
    
office_choose:    
    pattern:  /choose-office
    defaults: { _controller: DaVinciTaxiBundle:Office:office_choose }
office_passenger:
    pattern:  /office-passenger
    defaults: { _controller: DaVinciTaxiBundle:Office:office_passenger }
office_driver:
    pattern:  /office-driver
    defaults: { _controller: DaVinciTaxiBundle:Office:office_driver}
    
office_company:
    pattern:  /office-company
    defaults: { _controller: DaVinciTaxiBundle:Office:office_company }
block_profile:
    pattern:  /block-profile
    defaults: { _controller: DaVinciTaxiBundle:Office:block_profile }
filter_table:
    pattern:  /filter-table
    defaults: { _controller: DaVinciTaxiBundle:Office:filter_table }
order_table:
    pattern:  /order-table
    defaults: { _controller: DaVinciTaxiBundle:Office:order_table }
dispet_table:
    pattern:  /dispet-table
    defaults: { _controller: DaVinciTaxiBundle:Office:dispet_table }