da_vinci_taxi_homepage:
    resource: "@DaVinciTaxiBundle/Controller"
    type: annotation

passenger_request_payment:
    pattern: /payment/request_id/{id}
    defaults: { _controller: DaVinciTaxiBundle:Home:payment }
    methods:  [GET, POST]
    
passenger_request_generated:
    pattern: /generated
    defaults: { _controller: DaVinciTaxiBundle:Home:requestGenerated }
    methods:  [GET]
    
main_driver:
    pattern:  /main-driver
    defaults: { _controller: DaVinciTaxiBundle:Home:main_driver }    
profit:
    pattern:  /profit
    defaults: { _controller: DaVinciTaxiBundle:Information:profit }    

about:
    pattern:  /about
    defaults: { _controller: DaVinciTaxiBundle:Information:about }    
help:
    pattern:  /help
    defaults: { _controller: DaVinciTaxiBundle:Information:help }    
view_offices:
    pattern:  /view-offices
    defaults: { _controller: DaVinciTaxiBundle:Information:view_offices }    
video:
    pattern:  /video
    defaults: { _controller: DaVinciTaxiBundle:Information:video }    
guides:
    pattern:  /guides
    defaults: { _controller: DaVinciTaxiBundle:Information:guides }    
one_help:
    pattern:  /one-help
    defaults: { _controller: DaVinciTaxiBundle:Information:one_help }    
FAQs:
    pattern:  /FAQs
    defaults: { _controller: DaVinciTaxiBundle:Information:FAQs }    
notifications:
    pattern:  /notifications
    defaults: { _controller: DaVinciTaxiBundle:Information:notifications }    
information:
    pattern:  /information
    defaults: { _controller: DaVinciTaxiBundle:Information:information }    
financial_office:
    pattern:  /financial-office
    defaults: { _controller: DaVinciTaxiBundle:Information:financial_office }    
store:
    pattern:  /store
    defaults: { _controller: DaVinciTaxiBundle:Information:store }    

cmf_tree:
    resource: .
    type: 'cmf_tree'
sale_page:
    pattern:  /sale-page
    defaults: { _controller: DaVinciTaxiBundle:Information:sale_page }    
letter_confirm:
    pattern:  /letter-confirm
    defaults: { _controller: DaVinciTaxiBundle:Information:letter_confirm }    
new_ticket:
    pattern:  /new-ticket
    defaults: { _controller: DaVinciTaxiBundle:Information:new_ticket }    
