da_vinci_taxi_homepage:
    resource: "@DaVinciTaxiBundle/Controller"
    type: annotation

passenger_request_payment:
    pattern: /payment/request_id/{id}
    defaults: { _controller: DaVinciTaxiBundle:Home:payment }
    methods:  [GET, POST]
    options: { useAsInnerURL: false }
    
approve_request_status:
    pattern: /approve/request_id/{id}
    defaults: { _controller: DaVinciTaxiBundle:Home:approve }
    options: { useAsInnerURL: false }
    
cancel_request_status:
    pattern: /cancel/request_id/{id}
    defaults: { _controller: DaVinciTaxiBundle:Home:cancel }
    options: { useAsInnerURL: false }
    
decline_driver:
    pattern: /decline/driver/request_id/{id}
    defaults: { _controller: DaVinciTaxiBundle:Home:declineDriver }
    options: { useAsInnerURL: false }                
    
main_driver:
    pattern:  /main-driver
    defaults: { _controller: DaVinciTaxiBundle:Home:main_driver }  
    options: { useAsInnerURL: true } 
    
profit:
    pattern:  /profit
    defaults: { _controller: DaVinciTaxiBundle:Information:profit }    
    options: { useAsInnerURL: true }
        
about:
    pattern:  /about
    defaults: { _controller: DaVinciTaxiBundle:Information:about }    
    options: { useAsInnerURL: true }
        
help:
    pattern:  /help
    defaults: { _controller: DaVinciTaxiBundle:Information:help }    
    options: { useAsInnerURL: true }
        
view_offices:
    pattern:  /view-offices
    defaults: { _controller: DaVinciTaxiBundle:Information:view_offices }    
        
video_guides:
    pattern:  /video-guides
    defaults: { _controller: DaVinciTaxiBundle:Information:video_guides }    
    options: { useAsInnerURL: true }
        
guides:
    pattern:  /guides
    defaults: { _controller: DaVinciTaxiBundle:Information:guides }    
    options: { useAsInnerURL: true }
        
one_help:
    pattern:  /one-help
    defaults: { _controller: DaVinciTaxiBundle:Information:one_help }   
    
FAQs:
    pattern:  /FAQs
    defaults: { _controller: DaVinciTaxiBundle:Information:FAQs }    
    options: { useAsInnerURL: true }
        
notifications:
    pattern:  /notifications
    defaults: { _controller: DaVinciTaxiBundle:Information:notifications }    

social:
    pattern:  /social
    defaults: { _controller: DaVinciTaxiBundle:Information:social }    
    options: { useAsInnerURL: true }

reviews:
    pattern:  /reviews
    defaults: { _controller: DaVinciTaxiBundle:Information:reviews }    
    options: { useAsInnerURL: true }

blogs:
    pattern:  /blogs
    defaults: { _controller: ApplicationCmfBlogBundle:Information:blog }    
    options: { useAsInnerURL: true }        
        
financial_office:
    pattern:  /financial-office
    defaults: { _controller: DaVinciTaxiBundle:Information:financial_office }    
store:
    pattern:  /store
    defaults: { _controller: DaVinciTaxiBundle:Information:store }    
    options: { useAsInnerURL: true }

cmf_tree:
    resource: .
    type: 'cmf_tree'
sale_page:
    pattern:  /sale-page
    defaults: { _controller: DaVinciTaxiBundle:Information:sale_page }    
letter_confirm:
    pattern:  /letter-confirm
    defaults: { _controller: DaVinciTaxiBundle:Information:letter_confirm }    
new_ticket:
    pattern:  /new-ticket
    defaults: { _controller: DaVinciTaxiBundle:Information:new_ticket }    
