da_vinci_taxi_homepage:
    resource: "@DaVinciTaxiBundle/Controller"
    type: annotation
    
main_driver:
    pattern:  /main-driver
    defaults: { _controller: DaVinciTaxiBundle:Home:main_driver }    
profit:
    pattern:  /profit
    defaults: { _controller: DaVinciTaxiBundle:Home:profit }    
profit_driver:
    pattern:  /profit-driver
    defaults: { _controller: DaVinciTaxiBundle:Home:profit_driver }    
profit_passenger:
    pattern:  /profit-passenger
    defaults: { _controller: DaVinciTaxiBundle:Home:profit_passenger }    
about:
    pattern:  /about
    defaults: { _controller: DaVinciTaxiBundle:Home:about }    
help:
    pattern:  /help
    defaults: { _controller: DaVinciTaxiBundle:Home:help }    
view_offices:
    pattern:  /view-offices
    defaults: { _controller: DaVinciTaxiBundle:Home:view_offices }    
video:
    pattern:  /video
    defaults: { _controller: DaVinciTaxiBundle:Home:video }    
instructions:
    pattern:  /instructions
    defaults: { _controller: DaVinciTaxiBundle:Home:instructions }    
one_help:
    pattern:  /one-help
    defaults: { _controller: DaVinciTaxiBundle:Home:one_help }    
FAQs:
    pattern:  /FAQs
    defaults: { _controller: DaVinciTaxiBundle:Home:FAQs }    
notifications:
    pattern:  /notifications
    defaults: { _controller: DaVinciTaxiBundle:Home:notifications }    
information:
    pattern:  /information
    defaults: { _controller: DaVinciTaxiBundle:Home:information }    
financial_office:
    pattern:  /financial-office
    defaults: { _controller: DaVinciTaxiBundle:Home:financial_office }    
store:
    pattern:  /store
    defaults: { _controller: DaVinciTaxiBundle:Home:store }    
