da_vinci_taxi_homepage:
    pattern:  /
    defaults: { _controller: DaVinciTaxiBundle:Home:index }
    
order_step_1:
    pattern:  /order_step_1
    defaults: { _controller: DaVinciTaxiBundle:Home:order_step_1 }
order_step_2:
    pattern:  /order_step_2
    defaults: { _controller: DaVinciTaxiBundle:Home:order_step_2 }
order_step_3:
    pattern:  /order_step_3
    defaults: { _controller: DaVinciTaxiBundle:Home:order_step_3 }
main_driver:
    pattern:  /main_driver
    defaults: { _controller: DaVinciTaxiBundle:Home:main_driver }    

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
manager_step2:
    pattern:  /manager_step2
    defaults: { _controller: DaVinciTaxiBundle:Registration:manager_step2 }
taxidriver_step2:
    pattern:  /taxidriver_step2
    defaults: { _controller: DaVinciTaxiBundle:Registration:taxidriver_step2 }
company_step2:
    pattern:  /company_step2
    defaults: { _controller: DaVinciTaxiBundle:Registration:company_step2 }
company_step3:
    pattern:  /company_step3
    defaults: { _controller: DaVinciTaxiBundle:Registration:company_step3 }
independentdriver_step2:
    pattern:  /independentdriver_step2
    defaults: { _controller: DaVinciTaxiBundle:Registration:independentdriver_step2 }
    
    
office_choose:    
    pattern:  /choose-office
    defaults: { _controller: DaVinciTaxiBundle:Offices:office_choose }
office_company:
    pattern:  /office_company
    defaults: { _controller: DaVinciTaxiBundle:Offices:office_company }
block_profile:
    pattern:  /block_profile
    defaults: { _controller: DaVinciTaxiBundle:Offices:block_profile }
filter_table:
    pattern:  /filter_table
    defaults: { _controller: DaVinciTaxiBundle:Offices:filter_table }
order_table:
    pattern:  /order_table
    defaults: { _controller: DaVinciTaxiBundle:Offices:order_table }
dispet_table:
    pattern:  /dispet_table
    defaults: { _controller: DaVinciTaxiBundle:Offices:dispet_table }