DaVinci\TaxiBundle\Entity\PassengerRequest:
    properties:
        routePoints:
            - Collection:
                fields:
                    place:
                        - NotBlank:
                            groups: [ "flow_createPassengerRequest_step1"]
                            message: routePoints.place.blank
                allowMissingFields: false
        pickUpDate:
            - Date: 
                groups: [ "flow_createPassengerRequest_step1"]
                message: passengerRequest.pickUpDate.wrongFormat        
        pickUpTime:
            - Time: 
                groups: [ "flow_createPassengerRequest_step1"]
                message: passengerRequest.pickUpTime.wrongFormat        
        returnDate:
            - Date: 
                groups: [ "flow_createPassengerRequest_step1"]
                message: passengerRequest.returnDate.wrongFormat        
        returnTime:
            - Time: 
                groups: [ "flow_createPassengerRequest_step1"]
                message: passengerRequest.returnTime.wrongFormat