<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\OrderBundle\Entity;

use Sonata\OrderBundle\Entity\BaseOrderElement as BaseOrderElement;
use Doctrine\ORM\Mapping as ORM;
use Application\Sonata\OrderBundle\Entity\Order as Order;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 * @ORM\Entity
 */
class OrderElement extends BaseOrderElement
{
    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
}