fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_registration_register:
    pattern:  /register
    defaults: { _controller: DaVinciUserBundle:Registration:register }


fos_user_registration_confirm:
    pattern: /confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    methods:  [GET]

fos_user_registration_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    methods:  [GET,POST]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
    
#overwrite fosuser confirm email to choose-office 
DaVinciUserBundle:
  resource: "@DaVinciUserBundle/Controller"
  type: annotation