fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
fos_user_registration_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    methods:  [GET,POST]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
register_company:
    pattern: /register-company 
    defaults: { _controller: DaVinciUserBundle:Registration:register_company }
register_independent_driver:
    pattern: /register-independent-driver
    defaults: { _controller: DaVinciUserBundle:Registration:register_independent_driver }
register_manager:
    pattern: /register-manager
    defaults: { _controller: DaVinciUserBundle:Registration:register_manager }
register_company_driver:
    pattern: /register-company-driver
    defaults: { _controller: DaVinciUserBundle:Registration:register_company_driver }
    
    
#overwrite fosuser confirm email to choose-office 
DaVinciUserBundle:
  resource: "@DaVinciUserBundle/Controller"
  type: annotation
  
office_passenger:
    pattern:  /office-passenger
    defaults: { _controller: DaVinciUserBundle:Office:office_passenger }
office_driver:
    pattern:  /office-driver
    defaults: { _controller: DaVinciUserBundle:Office:office_driver}
    
office_company:
    pattern:  /office-company
    defaults: { _controller: DaVinciUserBundle:Office:office_company }
block_profile:
    pattern:  /block-profile
    defaults: { _controller: DaVinciUserBundle:Office:block_profile }
filter_table:
    pattern:  /filter-table
    defaults: { _controller: DaVinciUserBundle:Office:filter_table }
order_table:
    pattern:  /order-table
    defaults: { _controller: DaVinciUserBundle:Office:order_table }
dispet_table:
    pattern:  /dispet-table
    defaults: { _controller: DaVinciUserBundle:Office:dispet_table }